[package]
name = "idb-import-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
idb-parser = {git = "https://github.com/Vector35/idb-parser-rs.git"}
binaryninja = {git = "https://github.com/Vector35/binaryninja-api.git", branch = "dev"}
log = "0.4"